name: React CI/CD


on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Install dependencies
          run: npm install
          working-directory: ./frontend

        - name: Build React App
          run: npm run build
          working-directory: ./frontend

        - name: Verify dist/ exists
          run: |
            cd frontend
            ls -la
            echo "Contents of dist folder"
            ls -la dist/
            echo "contents of dist/assets:"
            ls -la dist/assets/
 
        - name: Add SSH Private Key
          uses: webfactory/ssh-agent@v0.7.0
          with:
            ssh-private-key: ${{secrets.SSH_PRIVATE_KEY}}
        
        - name: Test SSH Connection
          run: ssh -p ${{ secrets.SSH_PORT}} -o StrictHostKeyChecking=no ${{secrets.SERVER_USER}}@${{secrets.SERVER_IP}} "echo 'Connected Successfully'"

        - name: Deploy to VPS
          env:
            SERVER_IP: ${{ secrets.SERVER_IP}}
            SERVER_USER: ${{ secrets.SERVER_USER}}
            DEPLOY_PATH: ${{ secrets.DEPLOY_PATH}}
            SSH_PORT: ${{ secrets.SSH_PORT}}
          run:
           #rsync -avz -e "ssh -p $SSH_PORT" --delete dist/ $SERVER_USER@$SERVER_IP:$DEPLOY_PATH
           scp -P $SSH_PORT -o StrictHostKeyChecking=no  -r frontend/dist/ $SERVER_USER@$SERVER_IP:$DEPLOY_PATH
           #ssh $SERVER_USER@$SERVER_IP "sudo systemctl restart nginx"
          working-directory: ./frontend
