name: React CI/CD


on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Install dependencies
          run: npm install
          working-directory: ./frontend

        - name: Build React App
          run: npm run build
          working-directory: ./frontend

        - name: Generate SSH Key Pair
          run: |
            ssh-keygen -t rsa -b 4096 -C "github-actions@github.com" -f deploy_key -N ""
            {
              echo "PRIVATE_KEY<<EOF"
              cat deploy_key
              echo "EOF"
            } >> $GITHUB_ENV

            {
              echo "PUBLIC_KEY<<EOF"
              cat deploy_key.pub
              echo "EOF"
            } >> $GITHUB_ENV
        
        - name: Add Public Key to Server
          env:
            SERVER_IP: ${{ secrets.SERVER_IP}}
            SERVER_USER: ${{ secrets.SERVER_USER}}
            DEPLOY_PATH: ${{ secrets.DEPLOY_PATH}}
            SSH_PORT: ${{ secrets.SSH_PORT}}
          run: |
              mkdir -p ~/.ssh
              ssh-keyscan -p $SSH_PORT -H $SERVER_IP >> ~/.ssh/known_hosts
              echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
              chmod 600 ~/.ssh/id_rsa
              echo "$SSH_PORT"
              
              echo "SERVER_IP is set to: $SERVER_IP"
              echo "SERVER_USER is set to: $SERVER_USER"
              ssh -p $SSH_PORT $SERVER_USER@SERVER_ip
              #ssh -p $SSH_PORT $SERVER_USER@$SERVER_IP "mkdir -p ~/.ssh && echo '$PUBLIC_KEY' >> ~/.ssh/authorized_keys"
            
        - name: Deploy to VPS
          env:
            SERVER_IP: ${{ secrets.SERVER_IP}}
            SERVER_USER: ${{ secrets.SERVER_USER}}
            DEPLOY_PATH: ${{ secrets.DEPLOY_PATH}}
            SSH_PORT: ${{ secrets.SSH_PORT}}
          run:
           #rsync -avz -e "ssh -p $SSH_PORT" --delete dist/ $SERVER_USER@$SERVER_IP:$DEPLOY_PATH
           scp -P $SSH_PORT -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r dist/ $SERVER_USER@$SERVER_IP:$DEPLOY_PATH
           #ssh $SERVER_USER@$SERVER_IP "sudo systemctl restart nginx"
          working-directory: ./frontend
