name: React CI/CD


on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Install dependencies
          run: npm install
          working-directory: ./frontend

        - name: Build React App
          run: npm run build
          working-directory: ./frontend

        - name: Deploy to VPS
          env:
            SERVER_IP: ${{ secrets.SERVER_IP}}
            SERVER_USER: ${{ secrets.SERVER_USER}}
            DEPLOY_PATH: ${{ secrets.DEPLOY_PATH}}
            SSH_PORT: ${{ secrets.SSH_PORT}}
          run:
           #rsync -avz -e "ssh -p $SSH_PORT" --delete build/ $SERVER_USER@$SERVER_IP:$DEPLOY_PATH
            scp -p $SSH_PORT -r build/ $SERVER_USER@$SERVER_IP:$DEPLOY_PATH
           #ssh $SERVER_USER@$SERVER_IP "sudo systemctl restart nginx"
